version: '2'
services:
  redis:
    image: redis:3.0
  mysql:
    image: percona:5
    environment:
      - MYSQL_ROOT_PASSWORD=gurukami
    volumes:
      - /share:/share
  php56:
    image: gurukami/php:5.6
    links:
      - mysql
      - mongo
      - redis
    volumes:
      - /share:/share
      - /home:/home
      - /tmp/:/tmp/
  php:
    image: gurukami/php:7.0
    links:
      - mysql
      - mongo
      - redis
    volumes:
      - /share:/share
      - /home:/home
      - /tmp/:/tmp/
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  nginx:
    image: gurukami/nginx:latest
    depends_on:
      - php
    links:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /share:/share
